### ISSUE TITLE
[Bug]: Automatic dependency install fails (due to typo?)

### ISSUE THREAD

**Issue by gaufde** [chrisgrieser/alfred-quick-file-access#2]
### Checklist

- [X] I have updated to the [latest version of this workflow](./releases/latest).
- [X] I am using Alfred 5 or later.

### Alfred version

5.5.1 [2273]

### macOS version

13.7

### Bug Description

The Alfred Gallery dependency installer fails with a nondescript error.

### To Reproduce

When I use the built-in tool to install dependencies (https://www.alfredapp.com/help/kb/dependencies/), it shows me that at least one dependency is missing:
<img width="518" alt="image" src="https://github.com/user-attachments/assets/be601b8c-8f61-4146-8693-76a1fe79cbe5">

However, the installer fails with a nondescript error:
<img width="517" alt="image" src="https://github.com/user-attachments/assets/baba31c2-92b0-4314-9503-84ab8c60fca3">

The same dependency is listed on the Alfred gallery page with a broken link:
<img width="819" alt="image" src="https://github.com/user-attachments/assets/8c63725d-ee56-4e60-8089-d914fcc09dbc">

However, the workflow does work (after running `brew install ripgrep`), so it seems this probably a simple typo.

### Debugging Log

```Text
N/A
```

### Workflow Configuration

<img width="1194" alt="image" src="https://github.com/user-attachments/assets/d7443978-364e-4c08-b77a-bb9591b8c10d">

**Comment by chrisgrieser** [comment]
Thanks for pointing this out, this was a typo that was fixed in the workflow docs, but not in the respective Alfred Gallery info.

I created an issue at the Alfred Gallery repo: https://github.com/alfredapp/gallery-edits/issues/70

The Alfred team has to adopt the change at the Gallery. However, the Alfred team is usually pretty quick, so it should be fixed other there shortly. (Closing this issue, since there is nothing more that can be done on my end – please track the linked issue over there.)

**Comment by chrisgrieser** [comment]
fixed in the Alfred Gallery now

**Comment by gaufde** [comment]
The dependency resolution via Alfred works perfectly now as well!
