### ISSUE TITLE
[Bug]: Trash keyword doesn't work

### ISSUE THREAD

**Issue by gaufde** [chrisgrieser/alfred-quick-file-access#4]
### Checklist

- [X] I have updated to the [latest version of this workflow](./releases/latest).
- [X] I am using Alfred 5 or later.

### Alfred version

5.5.1 [2273]

### macOS version

Ventura 13.7.1

### Bug Description

The trash keyword isn't showing any results for me.

### To Reproduce

1. Open Alfred
2. Run the keyword associated with viewing files in the trash
3. ...no results appear

### Debugging Log

```Text
[16:31:25.920] Quick File Access[Script Filter] Queuing argument '(null)'
[16:31:26.077] Quick File Access[Script Filter] Script with argv '(null)' finished
[16:31:26.082] ERROR: Quick File Access[Script Filter] Code 1: KEYWORD: trash
SHELL COMMAND
find "$HOME/.Trash" "$HOME/Library/Mobile Documents/.Trash" -maxdepth 1 -mindepth 1
/Users/gaufde/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C9F49920-B488-4E89-8B70-97E528A1FE76/scripts/file-finder.js: execution error: Error: Error: find: /Users/gaufde/Library/Mobile Documents/.Trash: No such file or directory (1)
```

### Workflow Configuration

<img width="1200" alt="image" src="https://github.com/user-attachments/assets/19ceb45a-ba12-41cd-99a1-0f34e992ffe2">

**Comment by chrisgrieser** [comment]
Do you use iCloud drive?

**Comment by gaufde** [comment]
Yes, I do

**Comment by chrisgrieser** [comment]
Could you create a new file in the iCloud Drive, delete the file and then try the trash search again?

**Comment by gaufde** [comment]
Sure! I just followed that exact sequence of steps, but I'm still seeing this in the debugger:
```
[17:21:10.249] Quick File Access[Script Filter] Queuing argument '(null)'
[17:21:10.378] Quick File Access[Script Filter] Script with argv '(null)' finished
[17:21:10.383] ERROR: Quick File Access[Script Filter] Code 1: KEYWORD: trash
SHELL COMMAND
find "$HOME/.Trash" "$HOME/Library/Mobile Documents/.Trash" -maxdepth 1 -mindepth 1
/Users/gaufde/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C9F49920-B488-4E89-8B70-97E528A1FE76/scripts/file-finder.js: execution error: Error: Error: find: /Users/gaufde/Library/Mobile Documents/.Trash: No such file or directory (1)
```

**Comment by chrisgrieser** [comment]
Hmm, my assumption is that this is about you still using macOS 13, and that at macOS 13, the trash is at s as different location than at the current version. And since I do not have a device with 13, I unfortunately cannot check this myself. 

So it's a bit tricky trying to figure out where the trash location is in your device. 

Could you copy the path of a file in the iCloud Drive and post it here? Also, open the trash selected a file that you deleted from the iCloud Drive, and also post that path here

**Comment by gaufde** [comment]
> Hmm, my assumption is that this is about you still using macOS 13, and that at macOS 13, the trash is at s as different location than at the current version. And since I do not have a device with 13, I unfortunately cannot check this myself.

Could be, but I'm pretty sure I saw this same issue on a machine running some version of Sonoma last week. I can try to double check if needed, but it wasn't my machine.

In the meantime, here is a path to a file that is in iCloud:
```
/Users/gaufde/Library/Mobile Documents/com~apple~CloudDocs/untitled.txt
```

And here is the path to a file in the trash that came from iCloud:
```
/Users/gaufde/Library/Mobile Documents/com~apple~CloudDocs/.Trash/from trash.txt
```

**Comment by chrisgrieser** [comment]
> /Users/gaufde/Library/Mobile Documents/com~apple~CloudDocs/.Trash/

Yep, it appears that my suspicion was correct. I am on macOS 15, and on my device, the trash is located at `~/Library/Mobile Documents/com~apple~CloudDocs/.Trash/`

Since I only have definitive information on macOS 13 and 15 regarding the trash location, it might be that the location is incorrect on macOS 14. So if you could check the filepath of a trashed iCloud file on your macOS 14 device, that would be great.

Otherwise, I added a fix for macOS versions before 15, which should work for 13 and potentially 14.

Available in the Alfred Gallery in 1-2 days, or directly by downloading the latest release here: https://github.com/chrisgrieser/alfred-quick-file-access/releases/download/1.0.5/alfred-quick-file-access.alfredworkflow

**Comment by gaufde** [comment]
Awesome! This fix is already live and working for me.

Here is the info from a machine running Sonoma 14.5 (23F79):

```
~/Library/Mobile Documents/.Trash/Screenshot 2024-11-02 at 21.31.29 copy.png
~/Library/Mobile Documents/com~apple~CloudDocs/Downloads/Screenshot 2024-11-02 at 21.31.29 copy.png
```

**Comment by chrisgrieser** [comment]
Thanks for confirming. In that case, I guessed correctly that macOS 14 uses the same path as macOS 13, and the change apparently only came with 15.

Version 1.0.5 of the workflow should now work with all macOS versions then.

**Comment by gaufde** [comment]
Awesome! Your speed is both impressive and much appreciated :)

> Yep, it appears that my suspicion was correct. I am on macOS 15, and on my device, the trash is located at `~/Library/Mobile Documents/com~apple~CloudDocs/.Trash/`

Was this a typo? I was quite confused until I saw your new code suggests that macOS 15 drops the `com~apple~CloudDocs` part.

**Comment by chrisgrieser** [comment]
> Was this a typo? I was quite confused until I saw your new code suggests that macOS 15 drops the `com~apple~CloudDocs` part.

ah yes, it's a copypaste mistake. macOS 15 indeed drops the `com~apple~CloudDocs`, but apparently only for the trash location for whatever reason
