### ISSUE TITLE
Feature Request: exchange modifier keys

### ISSUE THREAD

**Issue by kzssc** [chrisgrieser/alfred-quick-file-access#5]
### Checklist

- [X] I have read the plugin's documentation.
- [X] The feature would be useful to more users than just me.

### Feature Requested

to use ⌘⏎ to reveal file in finder, ⌥⏎ to move the file to the front finder window. 
The reasoning is of consistency: ⌘⏎ for reveal in finder is default for alfred.

**Comment by chrisgrieser** [comment]
While I can see that can be annoying, switching around modifier keys would also be annoying for all the people already used to other the current ones. (And then make this workflow inconsistent with more than a dozen other ones which use a different modifier, etc.)

I think the better solution would be to advocate at the Alfred forum to make modifier keys customizable for users in general, since this issue cannot be satisfactorily addressed in Alfred workflows.
